name: drivesafe
description: A new Flutter project for DriveSafe application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.2
  firebase_analytics: ^11.0.0

  drift: 2.27.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0

  provider: ^6.1.2
  flutter_riverpod: ^2.5.1

  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  flutter_map: ^7.0.0
  latlong2: ^0.9.1

  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flex_color_scheme: ^7.3.1
  uuid: ^4.4.0
  flutter_material_color_picker: ^1.0.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  drift_dev: 2.27.0
  build_runner: ^2.4.11

  json_serializable: ^6.8.0
  analyzer: ^7.5.5

flutter:
  uses-material-design: true
